In [2]:
import numpy as np


Y=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])


#print Y
print()
print("Y = \n",Y)|
print()

print("Y has dimention:",Y.shape)
print("Y has a total of",Y.size,'element')
print('Y is an object of type:',type(Y))
print("The element in Y are of type:",Y.dtype)

SyntaxError: invalid syntax (<ipython-input-2-410170d5ee91>, line 9)

In [6]:
#array of zeros


x=np.zeros((3,4))#3 rows 4 columns
print(x)
#array of ones

y=np.ones((3,2))# 3 rows and 2 column
print(y)
#array of a specific number

z=np.full((2,3),5)
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]


In [7]:
#print q diagonally

x=np.eye(5)
print(x)


#diagonal matrix of desired number

y=np.diag([10,20,30,40])
print(y)

#arranging array chronologically

z=np.arange(10)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
#defined array range

x= np.arange(1,14,3)
print(x)

#plotting equal distant points from the start to end

y=np.linspace(0,25,10)
print(y)

[ 1  4  7 10 13]
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [10]:
#taking 10 points spaced equally between start and end excluding ending or starting

x=np.linspace(0,25,10,endpoint = False)
print(x)

#sequential integers from 0 to 19

y=np.arange(20)
print(y)


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
#reshapping x into a 4 X 5 ndarray

x = np.reshape(x, (4,5))
print(x)

#creating a rank 1 nd array with sequential integers from 0 to 19 and reshapping it to a 4 X 5 array
y = np.arange((20).reshape(4,5))
print(y)

ValueError: cannot reshape array of size 9 into shape (4,5)

In [14]:
#creating 3 X 3 matrix with random float values

x = np.random.random((3,3))
print(x)

#creating 3 X 3 matrix with random integer values

y=np.random.randint(4,15,size=(3,2))
print(y)

[[0.45343276 0.05401229 0.60851051]
 [0.98765126 0.09778855 0.00738087]
 [0.04675492 0.9948644  0.33659486]]
[[11 11]
 [10  8]
 [ 6 14]]


In [8]:
import numpy as np

#Mean of the given array

x = np.array([1,2,3,4,5])
y=x.mean()
print(y)

3.0


In [9]:
#Maximum from the given array

x = np.array([1,2,3,4,5])
y=x.max()
print(y)

5


In [10]:
#Minimum from the given array

x = np.array([1,2,3,4,5])
y=x.min()
print(y)

1


In [11]:
#Sum of the given array

x = np.array([1,2,3,4,5])
y=x.sum()
print(y)

15


In [12]:
#Number of Positive integers in the array

x = np.array([1,2,3,4,5])
y=(x>0).sum()
print(y)

5


In [13]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 3, 4, 5])
print(x[0])
print(x[-4])


1
2


In [15]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 3, 4, 5])
# We change the third element in x from 4 to 20

x[3] = 20

# We print x after it was modified 

print('Modified:\n x = ', x)


Modified:
 x =  [ 1  2  3 20  5]


In [16]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 3, 4, 5])

# We delete the first and last element of x

x = np.delete(x, [0,4])

print('Modified x = ', x)

Modified x =  [2 3 4]


In [17]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 3, 4, 5])

# We append the integer 6 to x

x = np.append(x, 6)

print(' x = ', x)

 x =  [1 2 3 4 5 6]


In [20]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 3, 4, 5])

# We append the integer 6 to x

x = np.append(x, 6)

print(' x = ', x)



 x =  [1 2 3 4 5 6]


In [22]:
# We create a rank 1 ndarray that contains integers from 1 to 5

x = np.array([1, 2, 5, 6, 7])
     
# We insert the integer 3 and 4 between 2 and 5 in x. 
      
x = np.insert(x,2,[3,4])

print("x = ", x)

x =  [1 2 3 4 5 6 7]


In [24]:
# We create a rank 1 ndarray 

x = np.array([1,2])

# We create a rank 2 ndarray 

Y = np.array([[3,4],[5,6]])

# We stack x on top of Y

z = np.vstack((x,Y))
print(z)
# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 

w = np.hstack((Y,x.reshape(2,1)))
print(w)

[[1 2]
 [3 4]
 [5 6]]
[[3 4 1]
 [5 6 2]]


In [27]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)

# We print X
print()
print('X = \n', X)
print()

# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)
# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)

# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [29]:
# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)
# We select all the elements in the 3rd column
q = X[:,2]
# We print q
print()
print('q = ', q)

# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]
# We print R
print()
print('R = \n', R)


v =  [10 11 12 13 14]

q =  [ 2  7 12 17]

R = 
 [[ 2]
 [ 7]
 [12]
 [17]]


In [30]:
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))



x =  [1 2 3 4 5]

y =  [6 7 2 8 4]
The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [31]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))
# We print X
print()
print('Original X = \n', X)
print()
# We sort the columns of X and print the sorted array
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 3  3  3 10  6]
 [ 8  2 10  4  2]
 [ 7  3 10  4  1]
 [ 9  5  7  8  2]
 [ 4  1  9  6  3]]

X with sorted columns :
 [[ 3  1  3  4  1]
 [ 4  2  7  4  2]
 [ 7  3  9  6  2]
 [ 8  3 10  8  3]
 [ 9  5 10 10  6]]
X with sorted rows :
 [[ 3  3  3  6 10]
 [ 2  2  4  8 10]
 [ 1  3  4  7 10]
 [ 2  5  7  8  9]
 [ 1  3  4  6  9]]
