In [ ]:
#Boolean indexing to assign the elements that are beween 10 to 17 the value of -1
import numpy as np

x[(x>10) & (x<17)] = -1

x = np.array([1,2,3,4,5])

#We create a rank 1 ndarray

y = np.array([6,7,2,8,4])

#We print x

print()
print("x = ",x)

#we print y

print()
print("y = ",y)

#We use set operations to compare x and y

print("The elements that are both in x and y",np.intersect1d(x,y))
print("The elements that are in x that are not in y :",np.setdiff1d(x,y))
print("All the element of x and y :",np.union1d(x,y))

In [5]:

x = np.random.randint(1,11,size = (5,5))

#print x

print()
print("Original x = \n",x)
print()

print("x with sorted coumns :\n",np.sort(x,axis=0))

print("X with sorted rows:\n",np.sort(x,axis=1))


Original x = 
 [[ 7  8  8  6  1]
 [ 3  8 10  5  1]
 [ 9  5  9  6  7]
 [ 1  8  5  2  7]
 [ 8  6  2  2  1]]

x with sorted coumns :
 [[ 1  5  2  2  1]
 [ 3  6  5  2  1]
 [ 7  8  8  5  1]
 [ 8  8  9  6  7]
 [ 9  8 10  6  7]]
X with sorted rows:
 [[ 1  6  7  8  8]
 [ 1  3  5  8 10]
 [ 5  6  7  9  9]
 [ 1  2  5  7  8]
 [ 1  2  2  6  8]]


In [7]:
# Pandas starts here

import pandas as pd

groceries = pd.Series(data=[30,6,'Yes','No'],index=['eggs','apples','milk','bread'])

groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [9]:
groceries.shape



(4,)

In [10]:
groceries.ndim


1

In [11]:
groceries.size


4

In [12]:
groceries.values


array([30, 6, 'Yes', 'No'], dtype=object)

In [13]:
groceries.index

Index(['eggs', 'apples', 'milk', 'bread'], dtype='object')

In [14]:
x = 'bananas' in groceries

y = 'bread' in groceries

print("Is bananas an index label in groceries :",x)
print("Is bread an index label in groceries :",y)

Is bananas an index label in groceries : False
Is bread an index label in groceries : True


In [15]:
groceries['eggs']

30

In [16]:
groceries[['milk','bread']]

milk     Yes
bread     No
dtype: object

In [17]:
groceries.loc[['eggs','apples']]

eggs      30
apples     6
dtype: object

In [18]:
groceries[[0,1]]

eggs      30
apples     6
dtype: object

In [19]:
groceries[[-1]]

bread    No
dtype: object

In [20]:
groceries.iloc[[2,3]]

milk     Yes
bread     No
dtype: object

In [21]:
groceries['eggs']=2

In [22]:
groceries.drop('apples')

eggs       2
milk     Yes
bread     No
dtype: object

In [23]:
print("Original grocery list:\n",groceries)

Original grocery list:
 eggs        2
apples      6
milk      Yes
bread      No
dtype: object


In [24]:
fruits = pd.Series(data=[10,6,3], index=['apples','oranges','bananas'])

In [25]:
fruits

apples     10
oranges     6
bananas     3
dtype: int64

In [26]:
fruits[['apples','oranges']]*2


apples     20
oranges    12
dtype: int64

In [29]:

#Starting Pandas DataFrame

import pandas as pd

item = {'Bob':pd.Series(data = [245,25,55], index = ['bike','pants','watch']),
       'Alice':pd.Series(data = [40,110,500,45], index = ['book','glasses','bike','pants'])}
item


{'Bob': bike     245
 pants     25
 watch     55
 dtype: int64,
 'Alice': book        40
 glasses    110
 bike       500
 pants       45
 dtype: int64}

In [31]:
shopping_carts = pd.DataFrame(item)
shopping_carts

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

In [32]:
shopping_carts.shape

(5, 2)

In [33]:
shopping_carts.ndim

2

In [34]:
shopping_carts.size

10

In [35]:
shopping_carts.values

array([[245., 500.],
       [ nan,  40.],
       [ nan, 110.],
       [ 25.,  45.],
       [ 55.,  nan]])

In [36]:
shopping_carts.index

Index(['bike', 'book', 'glasses', 'pants', 'watch'], dtype='object')

In [37]:
shopping_carts.columns

Index(['Bob', 'Alice'], dtype='object')

In [41]:
bob_shopping_cart = pd.DataFrame(item, columns = ['Bob'])

bob_shopping_cart

Bob
bike   245
pants   25
watch   55

In [42]:
sel_shopping_cart = pd.DataFrame(item,index = ['pants','books'])

In [43]:
sel_shopping_cart

Bob  Alice
pants  25.0   45.0
books   NaN    NaN

In [44]:
alice_sel_shopping_cart = pd.DataFrame(item,index = ['glasses','bike'], columns = ['Alice'])

In [45]:
alice_sel_shopping_cart

Alice
glasses    110
bike       500

In [48]:
item2=[{'bikes':20,'pants':30,'watches':35},
       {'watches':10,'glasses':50,'bikes':15,'pants':5}]

In [49]:
store_item = pd.DataFrame(item2,index = ['store 1','store 2'])

In [50]:
store_item

bikes  pants  watches  glasses
store 1     20     30       35      NaN
store 2     15      5       10     50.0

In [51]:
store_item['shirt']=[15,2]
store_item

bikes  pants  watches  glasses  shirt
store 1     20     30       35      NaN     15
store 2     15      5       10     50.0      2

In [53]:
store_item['suits'] = store_item['pants'] + store_item['shirt']
store_item

bikes  pants  watches  glasses  shirt  suits
store 1     20     30       35      NaN     15     45
store 2     15      5       10     50.0      2      7

In [54]:
new_item = [{'bikes':20,'pants':30,'watches':35,'glasses':4}]

In [55]:
new_store = pd.DataFrame(new_item, index = ['store 3'])

In [56]:
store_item = store_item.append(new_store)

In [57]:
store_item

bikes  pants  watches  glasses  shirt  suits
store 1     20     30       35      NaN   15.0   45.0
store 2     15      5       10     50.0    2.0    7.0
store 3     20     30       35      4.0    NaN    NaN

In [58]:
store_item.insert(4,'shoes',[8,5,0])

In [59]:
store_item

bikes  pants  watches  glasses  shoes  shirt  suits
store 1     20     30       35      NaN      8   15.0   45.0
store 2     15      5       10     50.0      5    2.0    7.0
store 3     20     30       35      4.0      0    NaN    NaN

In [60]:
store_item.pop('watches')

store 1    35
store 2    10
store 3    35
Name: watches, dtype: int64

In [61]:
store_item

bikes  pants  glasses  shoes  shirt  suits
store 1     20     30      NaN      8   15.0   45.0
store 2     15      5     50.0      5    2.0    7.0
store 3     20     30      4.0      0    NaN    NaN

In [63]:
store_item = store_item.drop(['watches','shoes'], axis = 1)
store_item

KeyError: "['watches'] not found in axis"

In [64]:
store_item = store_item.drop(['store 2','store 1'], axis = 0)
store_item

bikes  pants  glasses  shoes  shirt  suits
store 3     20     30      4.0      0    NaN    NaN

In [66]:
store_item = store_item.rename(columns = {'bikes':'hats'})
store_item

hats  pants  glasses  shoes  shirt  suits
store 3    20     30      4.0      0    NaN    NaN

In [67]:
store_item = store_item.rename(index = {'store 3':'last store'})
store_item

hats  pants  glasses  shoes  shirt  suits
last store    20     30      4.0      0    NaN    NaN

In [69]:
# Creating Python Dictonaries

item2 = [{'bikes':20,'pants':30,'watches':35,'shirt':15,'shoes':8,'suits':45},
        {'watches':10,'glasses':50,'bikes':15,'pants':5,'shirt':2,'shoes':5},
        {'bikes':20,'pants':30,'watches':35,'glasses':4,'shoes':10}]

store_item = pd.DataFrame(item2, index = ['store 1','store 2','store 3'])

store_item

bikes  pants  watches  shirt  shoes  suits  glasses
store 1     20     30       35   15.0      8   45.0      NaN
store 2     15      5       10    2.0      5    NaN     50.0
store 3     20     30       35    NaN     10    NaN      4.0

In [70]:
#check Null values

store_item.isnull()

bikes  pants  watches  shirt  shoes  suits  glasses
store 1  False  False    False  False  False  False     True
store 2  False  False    False  False  False   True    False
store 3  False  False    False   True  False   True    False